### ISSUE TITLE
Asynchronous Tasks

### ISSUE THREAD

**Issue by jslching** [qluvio/asynq#2]
As discussed, there is a need to implement asynchronous tasks for `asynq`

The idea is to be able to specify an `asynchronous` flag for tasks, such that when enabled, `asynq` will not mark the task as completed after the task handler returns, as would be normally done. Instead, the task will remain "active" until a subsequent call, e.g. `TaskCompleted()` or `TaskFailed()`, is called to signal that the task has been completed. This way, the task's goroutine will not necessarily have to block and wait for a completion event but can simply spin off an asynchronous process and then terminate, allowing for some other goroutine to signal the task completion at a later time

Otherwise, all other `asynq` functionality is expected to remain the same

**Comment by elv-gilles** [comment]
There should be "something"  to handle timeouts, when such an `asynchronous` task exits the `exec()` function of the asynq processor - and if the `TaskMessage` has a Timeout.

A solution could be to add a column `asynchronous` (boolean) to the `TasksTable` in rqlite (as was done for `recurrent`) and modify the implementation of the `*RQLite.Dequeue` function. _Note_: the 'recurrent' flag was not ported to the RDB implementation that supports Redis.

**Comment by jslching** [comment]
https://github.com/qluvio/content-fabric/issues/2344#issuecomment-1397206452
> @jslching after further discussion with Gilles, we can substantially simplify the required asynq changes. We don't have to add an `asynchronous` task type. Instead, it's simply the handler that decides (at runtime) whether a task is executed asynchronously or not. If asynchronous, it returns a special error (sentinel error), e.g. ErrAsynchronousTask. The processor, upon reception of the sentinel error, just simply skips updating the DB for the task.
> 
> We should keep the idea of passing an interface with `TaskCompleted` and `TaskFailed` functions in the ctx that is passed to the task handler, so that an asynchronous handler can store a reference to it somewhere that the completion trigger (i.e. node confirmation) can retrieve it from.
