### ISSUE TITLE
Upgrade asynq

### ISSUE THREAD

**Issue by jslching** [qluvio/asynq#4]
Currently, `rqlite-support` is based off of `v0.18.5`. In order to utilize newer features, e.g. `Retention` and `TaskID` task options, a minimum of `v0.19.0` will need to be merged. As of this comment, the latest version is `v0.24.0`

EDIT: After further discussion, it was decided that `v0.19.1` would be useful (though not required) to pull in currently. We will hold off on bringing in the latest, unless the `asynq` maintainers decide that our changes are desirable to them

**Comment by elv-gilles** [comment]
`v0.19.0` merged per #5
